language: cpp

compiler:
- clang

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
    - cmake --version
    - mkdir _builds
    - cd _builds
    - cmake ..

notifications:
  email:
    - sh.serg1993@gmail.com