language: cpp

compiler:
- clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sqlite3 qt5-dev-tools

script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake ..

notifications:
  email:
    - sh.serg1993@gmail.com