language: cpp
sudo: required
    
addons:
  apt:
    packages:
      - g++-6
    sources:
      - ubuntu-toolchain-r-test    
    
matrix:
  include:
    # Clang 3.8
    - os: linux
      env: UNIT_TESTS=true LLVM_VERSION=3.8.0 
      compiler: clang

    # GCC 6
    - os: linux
      env: UNIT_TESTS=true COMPILER=g++-6
      compiler: gcc

before_install: . scripts/ci/before_install.sh
install: . scripts/ci/install.sh
script: . scripts/ci/script.sh
after_success: . scripts/ci/after_success.sh

group: stable
