language: cpp

before_install: . scripts/ci/$TRAVIS_OS_NAME/before_install.sh
install: . scripts/ci/$TRAVIS_OS_NAME/install.sh
script: . scripts/ci/$TRAVIS_OS_NAME/script.sh
after_success: . scripts/ci/$TRAVIS_OS_NAME/after_success.sh

notifications:
  email:
    - sh.serg1993@gmail.com