language: cpp

before_install: . scripts/ci/before_install.sh
install: . scripts/ci/install.sh
script: . scripts/ci/script.sh
after_success: . scripts/ci/after_success.sh

notifications:
  email:
    - sh.serg1993@gmail.com