sudo: required
dist: trusty
os: linux
env: QT_VERSION=5
language: cpp
compiler: 
  - clang
  - gcc

before_install: . scripts/ci/before_install.sh
install: . scripts/ci/install.sh
script: . scripts/ci/script.sh
after_success: . scripts/ci/after_success.sh

group: stable
