language: cpp

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools

script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake ..

notifications:
  email:
    - sh.serg1993@gmail.com